image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8002
- port: 9001

vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - command: service nginx start &
  - command: cd /workspace/magento2gitpod && chmod a+rwx mysql-bashrc-launch.sh && ./mysql-bashrc-launch.sh
  - command: /usr/sbin/php-fpm7.3 --fpm-config php-fpm.conf &
  - command: rm -f /etc/php/7.3/cli/conf.d/20-tideways.ini && rm -f /etc/php/7.3/fpm/conf.d/20-tideways.ini
  - command: cd /workspace/magento2gitpod && wget -c https://magento.mirror.hypernode.com/releases/magento-2.3.5.tar.gz
  - command: chmod a+rwx menu.sh && ./menu.sh
